### PR TITLE
feat: enable GCC plugins

### PR DESCRIPTION
**Pull request by smira**
This is going to be used with kernel build.

Signed-off-by: Andrey Smirnov <smirnov.andrey@gmail.com>

### CODE REVIEW

**Review by Unix4ever — APPROVED** [review]

**Review by andrewrynhard — APPROVED** [review]
Do you have any docs on what this does for us?

**Comment by smira** [comment]
> Do you have any docs on what this does for us?

basically and my next PR enables support for GCC Plugins (look for that section in https://kernsec.org/wiki/index.php/Kernel_Self_Protection_Project/Recommended_Settings)

This allows us to have hardened kernel for sure with stack protection, etc.

**Comment by smira** [comment]
This option basically just enables some extra headers to be installed, it doesn't change gcc in any significant way

**Pull request merged**
